version: "2"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
    volumes:
      - namenode:/hadoop/dfs/name
      - ./hadoop-config/core-site.xml:/opt/hadoop-3.2.1/etc/hadoop/core-site.xml
      - ./hadoop-config/hdfs-site.xml:/opt/hadoop-3.2.1/etc/hadoop/hdfs-site.xml
      - ./hadoop-config/yarn-site.xml:/opt/hadoop-3.2.1/etc/hadoop/yarn-site.xml
    networks:
      - hadoop

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_namenode_rpc-address=namenode:9000
      - HDFS_CONF_dfs_datanode_address=datanode1:9866
      - HDFS_CONF_dfs_datanode_http_address=datanode1:9864
    volumes:
      - datanode1:/hadoop/dfs/data
      - ./hadoop-config/core-site.xml:/opt/hadoop-3.2.1/etc/hadoop/core-site.xml
      - ./hadoop-config/hdfs-site.xml:/opt/hadoop-3.2.1/etc/hadoop/hdfs-site.xml
    depends_on:
      - namenode
    networks:
      - hadoop

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    ports:
      - "8088:8088"
    environment:
      - CLUSTER_NAME=test
    depends_on:
      - namenode
      - datanode1
    networks:
      - hadoop

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager1
    ports:
      - "8042:8042"
    environment:
      - CLUSTER_NAME=test
    depends_on:
      - resourcemanager
      - datanode1
    networks:
      - hadoop

  jupyter:
    image: custom-jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=
      - JUPYTER_PASSWORD=
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0' --NotebookApp.port=8888 --NotebookApp.open_browser=False
    depends_on:
      - namenode
    networks:
      - hadoop

volumes:
  namenode:
  datanode1:

networks:
  hadoop:
